name: commercepal
description: An ecommerce site

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.7+32

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.1.0
  cupertino_icons: ^1.0.2

  # di
  injectable: ^2.1.0
  get_it: ^7.2.0

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0

  # ui
  flutter_screenutil: ^5.8.1
  animated_text_kit: ^4.2.2
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.2.3
  intl: ^0.19.0
  image_picker: ^1.0.7

  # network
  dio: ^4.0.0

  # databases
  floor: ^1.4.1
  sqflite: ^2.2.4+1
  flutter_secure_storage: ^9.0.0

  path_provider:
  fimber: ^0.7.0
  device_info_plus: ^9.1.1
  android_id: ^0.3.6
  phone_number: ^1.0.0
  email_validator: ^2.1.17
  url_launcher: ^6.1.9
  store_redirect: ^2.0.1
  sms_autofill: ^2.3.0
  otp_text_field: ^1.1.3
  flutter_google_places: ^0.3.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.2.0
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  font_awesome_flutter: ^10.6.0
  shared_preferences:
    ^2.2.2
    # Allows Google Translate without billing
  translator: ^0.1.5
  google_translator: ^1.0.0
  google_translate: ^0.0.3
  webview_flutter: ^2.0.12
  screenshot: ^2.1.0
  gallery_saver: ^2.0.1
  image: ^3.0.1

  # Unescape html characters
  html_unescape:
  another_stepper: ^1.2.2
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator:
  floor_generator:
  build_runner:
  freezed:
  test:

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/svgs/
    - assets/images/

  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sora-Light.ttf
          weight: 300
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
